### ISSUE TITLE
is there a way we can define the minimum length of password ? like in blockchain it must be at least 7 characters long 

### ISSUE THREAD

**Issue by umairnawaz786** [3rdIteration/btcrecover#134]
it ll save lots of time and system memory too !

**Comment by ChristophCaina** [comment]
I wouldn't implement something like that into the main source, since parameters like this should be given by the token file when you setup the tokens.

With this option, and depending on the already known password parts, you could setup the token file to try combinations with a minimum up to a maximum amount of characters.

**Comment by orangedecimation69** [comment]
You can use --regex-only "^.{7}" (7 being the minimum size you'd like to check)

**Comment by umairnawaz786** [comment]
thanks for the response orange !
python btcrecover.py --wallet wallet.aes.json --utf8 --blockchain-secondpass
how the command ll be with that token ?
and also how to define maximum limit ? can you write in reply ? i am not very technical about these commands , gotta learn a lot. lets say minimum length 7 and maximum 14 . kindly  write it here in answer

**Comment by orangedecimation69** [comment]
The command line would look like the following (I believe)
python btcrecover.py --wallet wallet.aes.json --utf8 --blockchain-secondpass --regex-only "^.{7,14}"

**Comment by 3rdIteration** [comment]
Added in https://github.com/3rdIteration/btcrecover/commit/806f45820cc0256545c5dacd82c8f4490f3ab107

**Comment by umairnawaz786** [comment]
no . it is still testing longer passwords
