### ISSUE TITLE
Some typos-maps slow the open-CL process with multiple GPUs down

### ISSUE THREAD

**Issue by lyncker** [3rdIteration/btcrecover#145]
Today I rented 2 vast.ai servers with several GPU (3090 and 1080). I was surprised , that the performnce with my test eviroment was that slow ! (the 1080 made 10 kps/s and the 3090 15 kp/s ).
After hours I figured out, that my typos-map file was the reason, but I dont know why... the original us-map.txt does not slow down the process (with this file the 3090 make around 70 kp/s). But the Seed example file slowed the also the process...

So I tried to change the US-map file to my needs and suddenly the file slowd my process down , too ... I wondered if this might be the format(utf8 or something) but it was not the problem. Finally I reduced the file down to one change ... here are the files

the fast one : 
`
aA	4
eE	3
iI	1
lL	1
y	z
Y	Z
z	y
Z	Y
r	ft54ed
`
and the slow one : 
`
aA	4
eE	3
iI	1
lL	1
y	z
Y	Z
z	y
Z	Y
r	ed
`
as you can see, only the last line is different ...

**Comment by lyncker** [comment]
no Idea??

**Comment by lyncker** [comment]
I figured out something more... if I just use my typo-map I get the full speed ( 34 kp/s) , but if I combine it with --typo 5 just let 5 typos per token happen , the speed reduces to 2 kp/s ...

**Comment by lyncker** [comment]
ok it does not have anything to do with open-cl ... If I use the password-map just with my cpu (I5) than the problem persists ...with --typos 5 and a typomap with 5 entries the process more or less stales ..

**Comment by 3rdIteration** [comment]
The issue is that you are hitting the bottleknecks in terms of how the candidate passwords are generated to be tested. Basically the generation is really basic, it just uses functions are are built in to Python to generate candidates and then strips out those that aren't valid, then starts doing the typo modifications required for the typos... Normally this doesn't matter for CPU processing, as the hashing is basically always the bottlekneck, but with GPU acceleration you will certainly bottlekneck at the generation step. (As the generation happens in a single cpu thread, so single core performance matters if you start to scale up with lot of GPUs)
