### ISSUE TITLE
Recover last 4 words from Ethereum seed

### ISSUE THREAD

**Issue by NovytskyiD** [3rdIteration/btcrecover#246]
Hi. 
I know first 8 words from seed.
I`m tried to input seed as - original leader remove powder trumpet morning amazing trophy 9 10 11 12, but search don`t start.
What to do in my case?

**Comment by 3rdIteration** [comment]
The math of four missing words is that it isn't a realistic recovery at this time using BTCRecover. (It will need to check 2048^4 possible seeds) If you want to use BTCRecover, your best bet is to wait 10 years and try again then with increased computing power.

Your only option is to use a cloud based pure OpenCL option like what is talked about here: https://medium.com/@johncantrell97/how-i-checked-over-1-trillion-mnemonics-in-30-hours-to-win-a-bitcoin-635fe051a752 (You would need to modify this code so that it would work with an Eth wallet)

**Comment by isieditors** [comment]
@NovytskyiD 
btcrecover is very slow for your case. johncantrell97's opencl is also slow. 
i have developed the right program for ETH seed recovery with the speed of 5 million per second. which means it can find 3 missing word in 28 minutes (at max) which I can do a demo for you.
it also  means it can find 4 missing word in 40 day (at max) with only 1 gpu and 20 days 2 gpu. 
if you want and if you pay for my trip I can bring my program to your place for safe recovery.
 : [walletsrecoveryservice@gmail.com](mailto:walletsrecoveryservice@gmail.com) walletsrecoveryservice(at)gmail(dot)com
