### ISSUE TITLE
cannot access watch-only wallet!

### ISSUE THREAD

**Issue by b4sh1t1** [3rdIteration/btcrecover#264]
Hello,

I get into this trouble since i create the BTCPayserver with docker; i managed to create the wallet with BTC, LTC and i have the recovery keys;

but seems i did create a store and didn't backup the recovery keys; but i know the passphrase (BIP39) for the wallet; and i remmeber i enabled the Import keys to RPC ; but don't know how to recover them from docker.

I transfer amount there through generate recieve BTC address and once the amount go inside my wallet i cannot send them!

Please assest me in this ASAP, i keep the wallet data in docker; i didn't replace it; all what i have now is the passphrase (BIP39) only;

Thanks all for your time in my issue!

**Comment by Stephen123489** [comment]
hi my name is Thomas i had this same issue a while ago which i solved on my own  kindly get back to me lets work something

**Comment by Stephen123489** [comment]
+1 (530) 901-9240‎ this is for whatsapp only                                                                                                                                      ‎But if you want my personal contact just let me know okay ??                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: b4sh1t1Sent: Sunday, October 17, 2021 15:09To: 3rdIteration/btcrecoverReply To: 3rdIteration/btcrecoverCc: Stephen123489; CommentSubject: Re: [3rdIteration/btcrecover] cannot access watch-only wallet! (#264)
send me your contacts please.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/3rdIteration/btcrecover/issues/264#issuecomment-945131827",
"url": "https://github.com/3rdIteration/btcrecover/issues/264#issuecomment-945131827",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 3rdIteration** [comment]
@b4sh1t1 you need to ignore the scammer... They are just going to rob you more.

You said that you both did backup the wallet keys and didn't, so which is it. Do you have a seed phrase or private keys at all?

**Comment by Stephen123489** [comment]
Whats going on ?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: b4sh1t1Sent: Tuesday, October 19, 2021 17:31To: 3rdIteration/btcrecoverReply To: 3rdIteration/btcrecoverCc: Stephen123489; CommentSubject: Re: [3rdIteration/btcrecover] cannot access watch-only wallet! (#264)
Hi dear,
Yes i did ignore him already, i just have the key password. and the seeds already deleted ... ?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/3rdIteration/btcrecover/issues/264#issuecomment-946897157",
"url": "https://github.com/3rdIteration/btcrecover/issues/264#issuecomment-946897157",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
