### ISSUE TITLE
Expand --exclude-password  functionality to work with seed recovery

### ISSUE THREAD

**Issue by AlloryDante** [3rdIteration/btcrecover#30]
I want to give you some ideeas for seedrecovery:

Output the tried conbinations for a passphrase
Somehow add an exclusion file so if you change the tokenlist.txt the old non-working combinations are not tried.

Thank you for this software

**Comment by 3rdIteration** [comment]
So I just renamed this and I'm thinking that what you are describing can be achieved in two ways. 

1) Including the --exclude-password list functionality in to seedrecover.py (It's already there for passwords, will require some modifications to duplicate check functionality before it will work with seedrecover)

2) Adding a seed limit command, basically the opposite to the --skip command. The thinking here is that you can use --listseeds to output the generated seeds, but stop at a specific number. (If say, you stopped your search after 10 billion tries) I'm loathed to add in any sort of feature that just dumps the results to the HDD as it goes, just because these sorts of files will get really, really large, really fast...)

**Comment by 3rdIteration** [comment]
Closed as stale issue
