### ISSUE TITLE
Searching randomly instead of in order (continuously)

### ISSUE THREAD

**Issue by UMPfw4** [3rdIteration/btcrecover#36]
I assume that based on the various parameters and inputs the search is conducted in a completely predictable order (i.e. if the same search for the missing words of a 12/24 word seed is performed twice, then the same combinations will be tried in the exact same order). I was wondering how to search in a randomized order (or something that resembles that). 

For example, if I estimate there are 100 Billion combinations for my search of the above missing words but I estimate I only have time/resources to search for 1B out of the 100B, then is there a way to search in some random way (non-ordered, non-continuous) so that my 1B of searched combinations are somewhat spread throughout the 100B total combinations? I.e. not 1B combinations all at the start, and not 1B all in the middle or end, or even starting at a specific number and proceeding continuously, but instead spread reasonably randomly?

In the above example, if 1B combinations are searched "in order / continuously", all of them might start with the same word because e.g. 3B combinations start with that word. I would like the option to search in a way that keeps shuffling stuff so that the searches are not concentrated to any particular word but spread to all of the eligible words  (based on the parameters etc).

If currently not possible (or you prefer not to add this functionality), could you suggest some way to achieve some similar effect manually (e.g. by doing multiple smaller searches or using tokenlists creatively etc)?

**Comment by cezarlacatus** [comment]
I am not an expert and also not a programmer, but statistically speaking, I don't really know if this method would help.
Currently the main focus of the project is on GPU acceleration, so I doubt that this will be implemented(if the developper would agree) anytime soon.

So my personal answer to this question, if you're interested would be to create multiple tokenfile configurations and launch different instances.

But if you know a little bit of python, you could find the array where the combination seeds are stored and add a function that will randomize entries.

This may help a little bit until you get the final answer from the developper

**Comment by 3rdIteration** [comment]
It mostly comes down to how the python permutations iterator, as documented here: https://docs.python.org/3/library/itertools.html#itertools.permutations The fact that it is deterministic is also actually useful if you are trying to use the --worker command and spread the load over multiple machines without them doubling up on anything.

Other than deviating from the behavior of the default python iterator (and having to write a completely new one) the other issue that will immediately arise is that of memory usage. Basically, if you ever want a search to end, you would need to keep track of every possible seed that you have tested. This is about 2 TB worth of seed phrases if for a seed phrase with three missing words... Even just storing a hash of them doesn't solve much, as you would still need to do the hashing for every random combination you came up with. The other issue is that the seed generator is already one of the bottleknecks in terms of brute-forcing seeds (This is becoming very apparent withe GPU acceleration), so we need to simplify it to speed it up, not complicate it to slow it down.

If you can come up with some deterministic iterator for Python3 that can iterate through all possible permutations in a different order, without having to worry about duplicates, than this is quite straight forward.

Rather than suggest a workaround, a better question would be what kind of recovery you are attempting?

**Comment by UMPfw4** [comment]
Thank you for the detailed explanation. This is indeed much more complicated than I thought, so no point in developing this. Just to answer your question I was going to use it in a specific situation of partial seed retrieval where I have to race against others with more computing power and the only way to get there first is by luck (i.e. randomly jumping to the correct combination without searching everything on the way like everyone else). I think some simple workarounds would achieve the same result without spending developing time, especially when there are other priorities as @cezarlacatus mentioned above. Thanks again for all the info.
