### ISSUE TITLE
Dogechain.info Password Not finding

### ISSUE THREAD

**Issue by witee-star** [3rdIteration/btcrecover#368]
Hey,
I copied JSON data from chrome. I pasted data in txt and also renamed as wallet.json wallet.aes.json wallet.txt dogewallet.json when I used btcrecover it's picking up wallet.Blockchain instead of wallet.Dogechain

**Comment by 3rdIteration** [comment]
Dogechain.info isn't supported for current wallets, thay changed their format.

See here https://github.com/3rdIteration/btcrecover/issues/317

**Comment by 3rdIteration** [comment]
Hey folks

So quick update on this. Basically it turns out that Dogechain.info wallets are still supported, but the method for downloading them has changed a bit. (An extra level of encryption has been added to the payload field, you can tell that your wallet has these in there as there are semicolons ";" in the payload JSON)

Basically the AES-CBC wallets will "just work", AES-GCM is still a work in progress.
