### ISSUE TITLE
Dogechain wallet recovery is not working 

### ISSUE THREAD

**Issue by sa976171** [3rdIteration/btcrecover#461]
Btcrecover is assuming dogechain json file as Blockchain wallet and unable to find password. Can you please fix it?

**Comment by 3rdIteration** [comment]
Duplicate of https://github.com/3rdIteration/btcrecover/issues/317

**Comment by 3rdIteration** [comment]
Hey folks

So quick update on this. Basically it turns out that Dogechain.info wallets are still supported, but the method for downloading them has changed a bit. (An extra level of encryption has been added to the payload field, you can tell that your wallet has these in there as there are semicolons ";" in the payload JSON)

Basically the AES-CBC wallets will "just work", AES-GCM is still a work in progress.
