### ISSUE TITLE
Random brute

### ISSUE THREAD

**Issue by roi35** [3rdIteration/btcrecover#72]
Hello, please make an option for bip39 seed brute force randomly from a known address requires an Address Database on openCl, please. if I did not notice this option, tell me how to start, with what parameters?

**Comment by 3rdIteration** [comment]
This is an entirely pointless exercise and already possible through the existing parameters. You simply set big-typos to the number of words in your seed and instead of typing your seed, just put in x for each word (or any non-BIP39 word)

If you have anything more than three missing words where the location is known, or two missing words where the location of the missing word is unknown, it will take years to run. Trying to brute-force an entire seed, even a 12 word one, from scratch, would require more time than life has existed on earth.
