### ISSUE TITLE
Sequence of words

### ISSUE THREAD

**Issue by kipilk0** [3rdIteration/btcrecover#8]
Hello, i have seed (12 words) randomly 
1-3-6-10-2...-4 etc
words are correct, how to restore valid phrase 1-12 ?

**Comment by 3rdIteration** [comment]
This will be included in the issue here: https://github.com/3rdIteration/btcrecover/issues/5 keep an eye out for it there.

I have a bit of a messy proof of concept that essentially uses the TokenList functionality to do this, might post an unsupported fork that can get the job done at a pinch if it is going to be more than a few weeks away
